on:
  release:
    types: [published]
    branches:
      - master
name: Test and Deploy on release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Test
      uses: actions/npm@master
      with:
        args: test
    - name: Deploy to ZEIT
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: now --prod --token ${ZEIT_TOKEN}
