function setCookie(cname, cvalue, exdays) {
  var d = new Date();
  d.setTime(d.getTime() + (exdays*24*60*60*1000));
  var expires = "expires="+ d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

function getCookieValue(a) {
  var b = document.cookie.match('(^|[^;]+)\\s*' + a + '\\s*=\\s*([^;]+)');
        return b ? b.pop() : '';
}

var sequence = getCookieValue("ibex_1_group");

switch (sequence){
        case "A":
            var shuffleSequence = seq("intro3", sepWith("sep", seq("practice", "intro4", randomize("Exp1_ListA_firstPair"), "pause", randomize("Exp1_ListA_secondPair"), "exitpoll", "sendResults", "end")));
            break;
        case "B":
            var shuffleSequence = seq("intro3", sepWith("sep", seq("practice", "intro4", randomize("Exp1_ListA_secondPair"), "pause", randomize("Exp1_ListA_firstPair"), "exitpoll", "sendResults", "end")));
            break;
        case "C":
            var shuffleSequence = seq("intro3", sepWith("sep", seq("practice", "intro4", randomize("Exp1_ListB_firstPair"), "pause", randomize("Exp1_ListB_secondPair"), "exitpoll", "sendResults", "end")));
            break;
        case "D":
            var shuffleSequence = seq("intro3", sepWith("sep", seq("practice", "intro4", randomize("Exp1_ListB_secondPair"), "pause", randomize("Exp1_ListB_firstPair"), "exitpoll", "sendResults", "end")));
            break;
        default:
            var shuffleSequence = seq("end");
                }

//var sequence = document.cookie.match('(^|[^;]+)\\s*group\\s*=\\s*([^;]+)');
//if (sequence=='AAA'){var shuffleSequence = seq("intro", sepWith("sep", seq("practice", randomize("ListA_secondPair"), randomize("firstPair"))));
//             } else if (sequence=='BBB'){var shuffleSequence = seq("intro", sepWith("sep", seq("practice", randomize("firstPair"), randomize("secondPair"))));}

var practiceItemTypes = ["practice"];

var defaults = [
    "Separator", {
        transfer: 1000,
        normalMessage: "Please wait for the next sentence.",
        errorMessage: "Wrong. Please wait for the next sentence."
    },
    "DashedSentence", {
        mode: "self-paced reading"
    },
    "AcceptabilityJudgment", {
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        instructions: "Use number keys or click boxes to answer.",
        leftComment: "(Bad)", rightComment: "(Good)"
    },
    "Question", {
        hasCorrect: true
    },
    "Message", {
        hideProgressBar: true
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: true
    }
];

var items = [

    ["sep", "Separator", { }],

    ["intro3", "Form", {
        html: { include: "intro3.html" },} ],

    ["intro4", "Form", {
        html: { include: "intro4.html" },} ],

    ["exitpoll", "Form", {
        html: { include: "exitpoll.html" },} ],

    ["end", "Form", {
        html: { include: "end.html" }, continueMessage: false} ],

	["sendResults", "__SendResults__", { }],

    ["practice", "DashedSentence", {s: "This is a practice sentence to get you used to reading sentences like this."}],
    ["practice", "DashedSentence", {s: "Please try to read as normally as possible."}],
    ["practice", "DashedSentence", {s: "This is another practice sentence with a practice question following it."},
                 "Question", {hasCorrect: false, randomOrder: false,
                              q: "How would you like to answer this question?",
                              as: ["Press 1 or click here for this answer.",
                                   "Press 2 or click here for this answer.",
                                   "Press 3 or click here for this answer."]}],
    ["practice", "DashedSentence", {s: "This is the last practice sentence before the experiment begins."}],

    //List A
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "John saw the absolute control of the company as a bad thing."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Carly found the arched roof of the courthouse amazing."}, "Question", {q: "Where was Carly?", as: ["in a courthouse", "in a classroom", "in a library"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Daniel wasn't very interested in the national elections although everyone was talking about them."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Gina trusted that the online magazine would print the truth."}, "Question", {q: "What was Gina reading?", as: ["a magazine", "a book", "a newspaper"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "According to the online survey the best pattern for winter this year is tartan."}, "Question", {q: "According to the survey, tartan is the best pattern for which season?", as: ["winter", "spring", "summer"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Despite the fact that the optimistic statement should have made her feel better Franzie was still worried about her essay grade."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Ms. Green says that the optimistic words might make all the difference in the courtroom."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Kyle liked the patterned paper he saw at the stationary store."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Ryan chose the patterned tie for his wedding outfit."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Mr. Griswold took notes on the planetary positions for his next paper."}, "Question", {q: "What is Mr. Griswold's career?", as: ["astronomer", "painter", "chef"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "A study of the planetary rings revealed their importance for future historical work."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Holly enjoyed the poetic genius in the author's most recent work."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Their astonished faces revealed the children's surprise at receiving such a nice gift."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It is widely known that poetic style is crucial to a book's success."}, "Question", {q: "What is crucial to a book's success?", as: ["nice poetic style", "a good plot line", "memorable characters"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Most of the time it was the practical affairs that took most of the administrator's time."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "In light of the practical matter consuming everyone's time the company barbecue was cancelled."}, "Question", {q: "What was cancelled?", as: ["a barbecue", "a meeting", "some practical affairs"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Convincing the reluctant readers that the book was enjoyable took some time."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Even the reluctant witness was able to be convinced to tell her story."}, "Question", {q: "Did the witness tell her story?", as: ["yes", "no"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The general opinion was that the ridiculous assertion should not be believed."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Getting the others to believe that the ridiculous prices were worth it was a difficult task."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Mr. Laughlin thinks that the rightful authority should be responsible for the cleanup."}, "Question", {q: "Who believes the rightful authority should be responsible for the cleanup?", as: ["Mr. Laughlin", "Ms. Lovedale", "Mr. Green"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Locating the rightful owner of the cat took a few minutes."}, "Question", {q: "What needed to be located?", as: ["the cat's owner", "the cat", "the suspect"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Tina always had scented candles in her room during the winter."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Noticing the astonished look on her friend's face the girl quickly stopped gossiping."}, "Question", {q: "Who had candles in her room in winter?", as: ["Tina", "Terry", "Lisa"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Valerie received scented lotions for her birthday yesterday."}, "Question", {q: "What did Valerie get for her birthday?", as: ["lotions", "perfumes", "books"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Leave it to the senior management to make everything more complicated."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Ms. Jefferson relies on senior staff to set the example for the rest of the hotel employees."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Billy wasn't used to the sentimental feelings he had after the romantic evening."}, "Question", {q: "How was Billy's evening?", as: ["romantic", "lonely", "boring"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The movie was about the sentimental love between two very different people."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Donald felt like a shady bench was all he could ask for."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Alisha went to the shady corner to get out of the sun for a moment."}, "Question", {q: "How was the weather?", as: ["sunny", "cold", "rainy"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Hadley explained that a shared membership allowed her and her boyfriend to both go to the same gym."}, "Question", {q: "Where did Hadley and her boyfriend want a shared membership to?", as: ["a gym", "a library", "a club"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "With a shared vision the manager could easily delegate tasks and complete the project."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The child liked the silky dress that came with the puppet."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Together the group tracked the astronomical observations on a large map spread across the table."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Katrina was inspired by the silky ears of a young lamb for her fabric choice."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "After a sizeable chunk collapsed the building was quickly evacuated."}, "Question", {q: "Why was the building evacuated?", as: ["a part collapsed", "someone saw smoke", "renovations were being made"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Although a sizeable portion had to be thrown away there was still enough food for everyone."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Nancy wasn't sure what the specific instructions had been but her students turned in very strange essays."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It was critical that the specific tasks be carried out exactly as described."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Of course the spectacular scenery made the vacation much nicer."}, "Question", {q: "How was the scenery?", as: ["great", "disappointing", "average"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Taking in the spectacular success Quinton jumped for joy in his new office."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "From the spindly limbs at the top of the tree the boy could see the whole town."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "A photograph of the spindly tree in the park hung over the couch."}, "Question", {q: "What picture hung over the couch?", as: ["a tree", "a wave", "a flower"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Angelina opted for the striped cloth for the skirt she was sewing."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The documentation included the astronomical units that had been measured."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Zo claimed that the striped stockings went well with my new white shoes."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "There must have been structural explanations that were previously unaccounted for."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Mr. Taylor gave a talk about the structural forces defining the bridge's strange shape."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Unfortunately a sudden gust blew the important financial documents away."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "If there isn't a sudden surge then the canoe should be fine."}, "Question", {q: "What poses a risk to the canoe?", as: ["a surge", "a storm", "a shark"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The two women decided that a suitable choice would be to restructure the class entirely."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It has been determined that a suitable framework cannot be found to answer this integral question."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Ms. Derry addressed the troubling issue of youth unemployment that was plaguing the city."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Discussing the troubling signs didn't lead to any sort of solution."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The man with the uncanny gift for languages answered the phone."}, "Question", {q: "What did the man have a gift for?", as: ["language", "mathematics", "the arts"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It makes sense that the attractive market was saturated with the competitor's product."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "With the uncanny precision of a calculator the student could work out complicated mathematical equations."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "My colleagues were checking out the attractive places to open an office."}, "Question", {q: "Who wanted to open an office?", as: ["some colleagues", "some doctors", "an insurance company"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Henry knew the bad idea would end up being a problem."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Jeff sensed the bad luck surrounding his recent business proposal."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Because of his bare arms the man got a terrible sunburn."}, "Question", {q: "Who got a sunburn?", as: ["a man", "a woman", "a child"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "James ensured absolute silence throughout the entire exam."}, "Question", {q: "Who ensured silence?", as: ["James", "Clara", "Frank"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Due to the guy's bare chest he was not allowed in the building."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "If the capable lawyer is on your side you should be able to win the case."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Given that the capable learners were working together the equation was easily solved."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "We were told to go to the cavernous auditorium and wait for the president's arrival."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The family viewed the cavernous lobby and took a lot of pictures."}, "Question", {q: "What did the family do?", as: ["take a lot of pictures", "have a long conversation",  "ask a lot of questions"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Last week I read about the celebrated essay written by the famous star."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "A few days ago the celebrated works were published for free electronically."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The interested individuals were told that certain circumstances are necessary for success in this day and age."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "There are certain conditions that we need to establish before we begin."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Randy didn't know why the competitive pressures on the team were so high."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Zach insisted upon an adequate supply before they left for the hike."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Tony told his brother that competitive spirit helped sell more product."}, "Question", {q: "Who was Tony talking to?", as: ["his brother", "his girlfriend", "his boss"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The man seated at the desk was given a complex machine to try to fix."}, "Question", {q: "What was the man trying to fix?", as: ["a machine", "a problem", "a pipe"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Katya created a complex set to stump the group of kids."}, "Question", {q: "Who was trying to stump the kids?", as: ["Katja", "Ms. Robbins", "Tia"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Lisa and Terry were concerned adults standing up for children's safety."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Katie didn't mind the concerned scientists complaining about the insufficient funding."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Apparently the confidential basis for the evidence discouraged the police officer."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The confidential conversations about the school didn't lead to a solution."}, "Question", {q: "Did the conversations lead to a solution?", as: ["no", "yes"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Thanks to the constructive comments the project was done way ahead of the deadline."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Jessica noted that the constructive suggestions had saved her a lot of time."}, "Question", {q: "Did the suggestions help Jessica?", as: ["yes", "no"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It seemed important that the democratic system would be upheld for years to come."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The book stated that an adequate training in first aid should be a priority."}, "Question", {q: "What did the book say should be a priority?", as: ["training in first aid", "have a safe workplace", "packing lots of food"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "As kids my sisters and I were taught that the democratic values should not be unchangeable."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Those disturbing dreams were always in the back of Ollie's mind."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Pollie explained the disturbing facts she heard a few years ago."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "No one noticed the dramatic changes in the amount of ice cream consumed per month."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It has been found that a dramatic increase in happiness occurs when someone sees a puppy."}, "Question", {q: "What happens when someone sees a puppy?", as: ["an increase in happiness", "a decrease in happiness",  "no change in mood"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The committee selected the eligible applicants from the pool of hopefuls."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Although there weren't any eligible recipients someone still had to get the prize."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "A picture of an endless horizon was hanging on the wall in the dentist's office."}, "Question", {q: "Where was the picture hanging?", as: ["in a dentist's  office", "in a nail salon", "in the living room"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Tori studied the endless maze with a thoughtful expression."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Hank doubted the erroneous assumptions would cause too much trouble."}, "Question", {q: "Did Hank think the assumptions would cause trouble?", as: ["no", "yes"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Sarah thought the annual growth was not very impressive."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The newspaper had printed the erroneous conclusion and had to publish an apology."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Last night an excellent article was posted reviewing the hit musical."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Jacob couldn't stop talking about the excellent chance he had been given."}, "Question", {q: "What had Jacob been given?", as: ["a chance", "a gift", "a choice"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Fiona's story revolved around the exclusive access she had gotten to a big party."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Sam told his friends about the exclusive club that was only for professional chess players."}, "Question", {q: "Who told his friends about the chess club?", as: ["Sam", "Trevor", "Paul"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Almost all experienced prosecutors know how to influence the jury."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Dara and Maria were regarded as experienced teachers and were always turned to for advice."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Given Sheila's extensive interviews with the recruiting agent it seemed likely she would get the job."}, "Question", {q: "Did it seem like Sheila would get the job?", as: ["yes", "no"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Having the extensive network of business connections made it easier for Becca to get promoted."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The woman with the long dark coat thought that the faint mist spreading over the lake was beautiful."}, "Question", {q: "What was the woman wearing?", as: ["a dark coat", "a long scarf", "both"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Susanne talked about the annual reports with too much enthusiasm."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Rick's father observed the faint shadows where the oil spill had been."}, "Question", {q: "Who observed the shadows?", as: ["Rick's father", "Rick's brother", "Tommie's brother"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Ignoring the frigid temperatures Heather went for a swim."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Rita figured that the frigid waters were keeping all the fish away."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "My new friend commented on the gorgeous name that my sister's baby has."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "My family admired the gorgeous picture that we took at the beach."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Mr. Edwards wrote about the gradual destruction of the trees in the park."}, "Question", {q: "What was being destroyed?", as: ["trees", "animals", "buildings"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It is often a gradual introduction of pollutants that ruins the groundwater."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Ms. Thompson used the handy feature to control her car's speed."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Everyone had heard about the apparent conflict between the president and his staff."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Most of the participants were told about the handy reference that could simplify their task."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "The class focused on the importance of healthy eating and how to achieve it."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The topic of healthy weight has become very important in the past decade."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It had been shown that heightened awareness does not lead to a lower rate of theft."}, "Question", {q: "Does awareness lead to less theft?", as: ["no", "yes"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "To ensure heightened visibility of the problem the blogger spread the post all over the internet."}, "Question", {q: "Who spread the post?", as: ["the blogger", "the scientist", "the expert"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Beth grabbed the hooded parka and ran out the door."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Trevor had the hooded sweatshirts packed in his suitcase in case it got cold."}, "Question", {q: "What had Trevor packed?", as: ["warm clothes", "his swimsuit", "thick blankets"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Because her immediate attention was directed at the patient the doctor couldn't help the nurse."}, "Question", {q: "Could the doctor help the nurse?", as: ["no", "yes"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Mr. Kerry's immediate problem was the student refusing to do his homework."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It was only natural that increased education led to a more engaged and interested community."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Despite the apparent failure of the blockbuster movie many tickets were sold."}, "Question", {q: "Were many tickets sold?", as: ["yes", "no"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "There seemed to be no connection between increased use and better command of the strange device."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Matteo's friend disregarded the inherent contradiction and continued doing things as he always had done."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "When the inherent risk was made clear Clara made sure to document it."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "For many years the innovative approaches were highly praised by experts."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "From the first day the innovative programs changed the way new recruits were trained."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Ralph's left eye was injured but that didn't stop him from playing baseball."}, "Question", {q: "Which sport did Ralph want to play?", as: ["baseball", "basketball", "football"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "The report showed that her left knee was not functioning as well as it should be."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Darla wasn't bothered by the lengthy delay because she had a good book to read."}, "Question", {q: "What did Darla do as she waited?", as: ["read a book", "listened to music", "had a conversation"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Once the lengthy passage was over the article got a lot more enjoyable."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It wasn't clear what the literal connection was but the argument seemed sound."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Julia drew the arched ceilings of the cathedral in her sketchbook."}, "Question", {q: "What did Julia draw?", as: ["a building", "a nature scene", "a person"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "Mr. Henly outlined the literal interpretations and what it meant for the customer."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "It was surprising that the loyal following didn't change their impression of the superstar."}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "It became clear that the loyal subjects were suffering under the new king's harsh rule."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Four years ago they established that the mandatory course was unnecessary and could be abolished."}, "Question", {q: "When was it established that the course was unnecessary?", as: ["four years ago", "last week", "a couple months ago"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "In reality the mandatory testing didn't seem relevant to Chase's degree."}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "Ms. Archilego searched for the mythological scenes in the new museum wing."}, "Question", {q: "Where was Ms. Archilego?", as: ["in a museum", "in her office", "in the library"]}],
    ["Exp1_ListA_secondPair", "DashedSentence", {s: "My professor pointed out the mythological terms that the journalist consistently used incorrectly."}, "Question", {q: "Who used the terms incorrectly?", as: ["the journalist", "my professor", "me"]}],
    ["Exp1_ListA_firstPair", "DashedSentence", {s: "A lot of attention was given to the national debate across all sources of media."}],


    //List B
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "James ensured absolute control throughout the entire process."}, "Question", {q: "Who ensured control throughout the process?", as: ["James", "Jeffry", "Jessica"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Julia drew the arched roof of the cathedral in her sketchbook."}, "Question", {q: "What did Julia draw?", as: ["a building", "an animal", "a plant"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "A lot of attention was given to the national elections across all sources of media."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "According to the online magazine the best pattern for winter this year is tartan."}, "Question", {q: "According to the magazine, tartan is the best pattern for which season?", as: ["winter", "spring", "summer"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Gina trusted that the online survey would reveal the truth."}, "Question", {q: "What did Gina trust?", as: ["a survey", "a book", "an article"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Ms. Green says that the optimistic statement might make all the difference in the courtroom."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Despite the fact that the optimistic words should have made her feel better Franzie was still worried about her essay grade."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Ryan chose the patterned paper for his wedding invitation."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Kyle liked the patterned tie he saw at the luxury store."}, "Question", {q: "Where was Kyle shopping?", as: ["a luxury store", "a grocery store", "a discount store"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "A study of the planetary positions revealed their importance for the planet's weather."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Mr. Griswold took notes on the planetary rings for his next paper."}, "Question", {q: "What is Mr. Griswold's career?", as: ["astronomer", "painter", "chef"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It is widely known that poetic genius is rare in today's literary circle."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Noticing the astonished faces her friends were giving her the girl stopped gossiping."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Holly enjoyed the poetic style in the author's most recent work."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "In light of the practical affairs consuming everyone's time the company barbecue was cancelled."}, "Question", {q: "What was cancelled?", as: ["a barbecue", "a meeting", "a course"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Most of the time it was the practical matter that took most of the administrator's time."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Even the reluctant readers were able to be won over by the story."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Convincing the reluctant witness that her testimony was necessary took some time."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Getting the others to believe that the ridiculous assertion was actually true was a difficult task."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The general opinion was that the ridiculous prices should not be paid."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Locating the rightful authority for the ruling took a few weeks."}, "Question", {q: "How long did it take to find the proper authority?", as: ["a few weeks", "a  few hours", "a few months"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Mr. Laughlin thinks that the rightful owner should be responsible for the dog."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Valerie received scented candles for her birthday yesterday."}, "Question", {q: "What did Valerie get for her birthday?", as: ["candles", "chocolate", "a new phone"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Their astonished look revealed the children's surprise at receiving such a nice gift."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Tina always had scented lotions in her bag during the winter."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Ms. Jefferson relies on senior management to set the example for the rest of the hotel employees."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Leave it to the senior staff to make everything more complicated."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The movie was about the sentimental feelings of falling in love again."}, "Question", {q: "What was the movie about?", as: ["love", "mystery", "adventure"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Billy wasn't used to the sentimental love he felt after the romantic evening."}, "Question", {q: "How was Billy's evening?", as: ["romantic", "boring", "lonely"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Alisha went to the shady bench to get out of the sun for a moment."}, "Question", {q: "How was the weather?", as: ["sunny", "cold", "rainy"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Donald felt like a shady corner was all he could ask for."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "With a shared membership the coworkers could all go to the expensive gym together."}, "Question", {q: "What did the coworkers want to share a membership for?", as: ["a gym", "a library", "a club"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Hadley explained that a shared vision ensured her and the other project members stayed on the same page."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Katrina was inspired by the silky dress hanging in the wind for her next painting."}, "Question", {q: "Who was inspired by the dress?", as: ["Katrina", "Catherine", "Louisa"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The documentation included the astronomical observations that had been made."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The child liked the silky ears of the family's pet dog."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Although a sizeable chunk had to be thrown away there was still enough food for everyone."}, "Question", {q: "Was there enough food?", as: ["yes", "no"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "After a sizeable portion collapsed the building was quickly evacuated."}, "Question", {q: "Why was the building evacuated?", as: ["a part collapsed", "someone saw smoke", "renovations were being made"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It was critical that the specific instructions be carried out exactly as described."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Nancy wasn't sure what the specific tasks had been but her students turned in very strange essays."}, "Question", {q: "What is Nancy reading?", as: ["strange essays", "an interesting article", "classic literature"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Taking in the spectacular scenery Quinton stared out the window of the bus."}, "Question", {q: "Where was Quinton?", as: ["in a bus", "at a park", "in a house"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Of course the spectacular success made the grant more likely."}, "Question", {q: "Was the grant likely?", as: ["yes", "no"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "A photograph of the spindly limbs of the tree hung over the couch."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "From the spindly tree on the top of the hill the boy could see the whole town."}, "Question", {q: "What could the boy see?", as: ["the whole town", "an empty field", "a busy street"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Zo claimed that the striped cloth would be perfect for my new shirt."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Together the group tracked the astronomical units of the star system spread across the galaxy."}, "Question", {q: "What was the group tracking?", as: ["a star system", "a wild animal", "the spread of the city"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Angelina opted for the striped stockings to go with her high heels."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Mr. Taylor gave a talk about the structural explanations for the bridge's strange shape."}, "Question", {q: "Who gave the talk?", as: ["Mr. Taylor", "Mr. Rodriguez", "Ms. Thompson"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "There must have been structural forces that were previously unaccounted for."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "If there isn't a sudden gust then the tower should be fine."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Unfortunately a sudden surge blew the ship out to sea."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It has been determined that a suitable choice cannot be made before we ask the client."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The two women decided that a suitable framework was needed to restructure the class entirely."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Discussing the troubling issue didn't lead to any sort of change."}, "Question", {q: "Did discussing the issue lead to change?", as: ["no", "yes"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Ms. Derry addressed the troubling signs of youth unemployment that were plaguing the city."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "With the uncanny gift for learning a language the student could speak Japanese nearly fluently."}, "Question", {q: "What language could the student speak?", as: ["Japanese", "Korean", "Hindi"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "My colleagues were checking out the attractive market to launch a product."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The man with the uncanny precision in mathematics answered my question."}, "Question", {q: "What was the man talented at?", as: ["mathematics",  "science", "literature"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It makes sense that the attractive places to live are generally densely populated."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Jeff sensed the bad idea included in his business proposal."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Henry knew the bad luck would probably not stick around forever."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Due to the guy's bare arms you could see his large tribal tattoo."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "John saw the absolute silence of the children as a bad sign."}, "Question", {q: "What did John think was a bad sign?", as: ["the children's silence", "the loud music", "the negative reviews"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Because of his bare chest the man got a terrible sunburn."}, "Question", {q: "Who got a sunburn?", as: ["a man", "a woman", "a child"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Given that the capable lawyer was working for her the jury was convinced."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "If the capable learners are in your group you should be able to teach them easily."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The family viewed the cavernous auditorium and took a lot of pictures."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "We were told to go to the cavernous lobby and wait for the president's arrival."}, "Question", {q: "Who was arriving?", as: ["the president", "a professor", "a doctor"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "A few days ago the celebrated essay were published for free electronically."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Last week I read about the celebrated works written by the famous novelist."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "There are certain circumstances that we need to have before we begin."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The interested individuals were told that certain conditions are necessary for success in this day and age."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Tony told his brother that competitive pressures helped sell more product."}, "Question", {q: "Who was Tony talking to?", as: ["his brother", "his friend", "his boss"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The book stated that an adequate supply of fresh water should be a priority."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Randy didn't know why the competitive spirit in the team was so high."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Katya created a complex machine to sort a deck of cards."}, "Question", {q: "Who created a machine to sort cards?", as: ["Katya", "Carla", "Sita"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The man seated at the desk was given a complex set to put in order."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Katie didn't mind the concerned adults complaining about school lunch quality."}, "Question", {q: "What were the adults complaining about?", as: ["school lunch", "parking spaces", "gym class"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Lisa and Terry were concerned scientists standing up for academic integrity."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The confidential basis for the discussion didn't stop Kamar listening in."}, "Question", {q: "Who didn't stop listening in?", as: ["Kamar", "Devon", "Trey"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Apparently the confidential conversations between the parties discouraged the police officer."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Jessica noted that the constructive comments had saved her a lot of time."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Thanks to the constructive suggestions the project was done way ahead of the deadline."}, "Question", {q: "Was the project done on time?", as: ["yes", "no"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "As kids my sisters and I were taught that the democratic system should not be unchangeable."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Zach insisted upon an adequate training before they left for the hike."}, "Question", {q: "Who insisted upon training?", as: ["Zach", "Jeff", "James"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It seemed important that the democratic values would be valued for years to come."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Pollie explained the disturbing dreams she had a few years ago."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Those disturbing facts were always in the back of Ollie's mind."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It has been found that a dramatic changes in happiness occurs when someone sees a puppy."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "No one noticed the dramatic increase in the amount of ice cream consumed per month."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Although there weren't any eligible applicants someone still had to get the prize."}, "Question", {q: "Did someone get the prize?", as: ["yes", "no"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The committee selected the eligible recipients from the pool of hopefuls."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Tori studied the endless horizon with a worried expression."}, "Question", {q: "Who was worried?", as: ["Tori", "Jackie", "Jessica"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "A picture of an endless maze was hanging on the wall in the dentist's office."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The newspaper had printed the erroneous assumptions and had to publish an apology."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Susanne talked about the annual growth with too much enthusiasm."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Hank doubted the erroneous conclusion would cause too much trouble."}, "Question", {q: "Did Hank think the conclusion would cause a lot of trouble?", as: ["no", "yes"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Jacob couldn't stop talking about the excellent article he had been reading."}, "Question", {q: "What had Jacob been reading?", as: ["a good article", "a new book", "an instructional pamphlet"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Last night an excellent chance was posted on the job website."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Sam told his friends about the exclusive access that he had gained to the society."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Fiona's story revolved around the exclusive club she had found on the main street."}, "Question", {q: "What had Fiona found?", as: ["a club", "a restaurant", "a store"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Dara and Maria were regarded as experienced prosecutors and were always turned to for advice."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Almost all experienced teachers know how to motivate their students."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Having the extensive interviews with her supervisors made it more likely that Becca got promoted."}, "Question", {q: "What helped Becca get promoted?", as: ["the interviews", "her performance", "her luck"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Given Sheila's extensive network of highly skilled colleagues it seemed likely she would get the project."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Rick's father observed the faint mist where the leak seemed to be."}, "Question", {q: "Who observed the mist?", as: ["Rick's father", "Rick's brother", "Tommie's brother"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Sarah thought the annual reports were not very impressive."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The woman with the long dark coat thought that the faint shadows cast under the tree were beautiful."}, "Question", {q: "What was the woman wearing?", as: ["a dark coat", "a long scarf", "both"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Rita figured that the frigid temperatures were keeping all the birds away."}, "Question", {q: "Why were there no birds?", as: ["it was cold", "it was raining", "it was sunny"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Ignoring the frigid waters Heather went for a swim."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "My family admired the gorgeous name that we gave to the baby."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "My new friend commented on the gorgeous picture in my sister's renovated kitchen."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It is often a gradual destruction of species that leads to extinction."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Mr. Edwards wrote about the gradual introduction of tropical birds to the park."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Most of the participants were told about the handy feature that could simplify their task."}, "Question", {q: "Were all the participants told about the helpful feature?", as: ["no", "yes"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Despite the apparent conflict between the two friends she attended the wedding."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Ms. Thompson used the handy reference to calculate her car's efficiency."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The topic of healthy eating has become very important in the past decade."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "The class focused on the importance of healthy weight and how to maintain it."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "To ensure heightened awareness of the problem the blogger spread the post all over the internet."}, "Question", {q: "Who spread the post?", as: ["the blogger", "the scientist", "the expert"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It had been shown that heightened visibility does not lead to a lower rate of theft."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Trevor had the hooded parka packed in his suitcase in case it got cold."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Beth grabbed the hooded sweatshirts and ran out the door."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Mr. Kerry's immediate attention was on the student refusing to do homework."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Because her immediate problem was directed at the patient the doctor couldn't help the nurse."}, "Question", {q: "Could the doctor help the nurse?", as: ["no", "yes"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "There seemed to be no connection between increased education and better job outcomes in the city."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Everyone had heard about the apparent failure of the greatly anticipated romance novel."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It was only natural that increased use led to a deeper understanding of the software."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "When the inherent contradiction was made clear Clara made sure to document it."}, "Question", {q: "Who documented the contradiction?", as: ["Clara", "Keith", "Jenna"]}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Matteo's friend disregarded the inherent risk and continued doing things as he always had done."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "From the first day the innovative approaches changed the way new recruits were trained."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "For many years the innovative programs were highly praised by experts."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "The report showed that her left eye was not functioning as well as it should be."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Ralph's left knee was injured but that didn't stop him from playing baseball."}, "Question", {q: "Which sport did Ralph want to play?", as: ["baseball", "basketball", "football"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Once the lengthy delay was over the team could all board the plane."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Darla wasn't bothered by the lengthy passage in the book because the prose was enjoyable."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Mr. Henly outlined the literal connection and what it meant for the customer."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Carly found the arched ceilings of the courthouse amazing."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It wasn't clear what the literal interpretations was but the argument seemed sound."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "It became clear that the loyal following had only been getting larger since the incident."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "It was surprising that the loyal subjects didn't betray their king despite the pressure."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "In reality the mandatory course didn't seem relevant to Chase's degree."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Four years ago they established that the mandatory testing was unnecessary and could be abolished."}, "Question", {q: "When was it established that the testing was unnecessary?", as: ["four years ago", "last week", "a couple months ago"]}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "My professor pointed out the mythological scenes that the sculpture was based on."}],
    ["Exp1_ListB_secondPair", "DashedSentence", {s: "Ms. Archilego searched for the mythological terms in the new fictional novel."}],
    ["Exp1_ListB_firstPair", "DashedSentence", {s: "Daniel wasn't very interested in the national debate although everyone was talking about it."}],

];
